### PR TITLE
Fix an error with the coordinates of the arc.

### PR DESCRIPTION
**Pull request by lecarrera-tec**
Is the issue #46 fixed. The x position should use cos while the y position should use sin.

### CODE REVIEW

**Comment by johannes-wolf** [comment]
Some of the tests fail because the origin of the arc changed to its end.

**Comment by lecarrera-tec** [comment]
I could fix local-anchor and primitive examples. I'm trying to understand the ring example, but I believe the right solution is to replace the ref.png image. With that, all the examples run correctly, well except for the image test that give me this error:
[TEST] image ...
Syntax Warning: Read from memory error. Got 0 bytes, block should be of 128 bytes
Syntax Warning: read ICCBased color space profile error

**Comment by johannes-wolf** [comment]
The warning is “normal”, I also get it.
Can you push your fixes? Updating the ref image is fine.

**Comment by johannes-wolf** [comment]
@fenjalien Are you using the `arc` function in `circuitypst`; is this change compatible?

**Comment by fenjalien** [comment]
Thanks for the bug fix! It is technically my fault...

Go ahead with the merge, I'll make a fix to circuitypst.

**Pull request merged**
