### PR TITLE
plot: Heatmap

### PR DESCRIPTION
**Pull request by johannes-wolf**
Implements a basic heatmap by drawing rects.
This is not a good solution for heatmaps with more than 15×15 tiles, as the performance is not as good for lots of rect calls.

### CODE REVIEW

**Comment by Enivex** [comment]
I posted this feature request, which would make this vastly more performant

https://github.com/typst/typst/issues/2575

**Comment by johannes-wolf** [comment]
> I posted this feature request, which would make this vastly more performant
> 
> [typst/typst#2575](https://github.com/typst/typst/issues/2575)

Thank you! I think bitmap images are the only performant option for high-res heatmaps. Even if cetz would be fast enough, the PDF would be slow to render.

**Comment by Enivex** [comment]
I guess this was blocked by https://github.com/typst/typst/issues/2575 not yet being resolved?

**Comment by johannes-wolf** [comment]
I've closed this by accident. Although, the current API is not that good for generating bitmaps, as it does not support raw pixel data. Having to convert to PNG/JPG first seems to be unnecessary complex.

**Comment by johannes-wolf** [comment]
I've closed this by accident. Although, the current API is not that good for generating bitmaps, as it does not support raw pixel data. Having to convert to PNG/JPG first seems to be unnecessary complex.

**Comment by JamesxX** [comment]
Is this something a WASM plugin could deal with?

**Comment by johannes-wolf** [comment]
> Is this something a WASM plugin could deal with?

Yes. A plug-in that takes a matrix and returns a bitmap would be cool.

**Pull request closed without merging**
